const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {createWebsiteVault}=require('../src/website-vault');
const {createWebsiteLogin}=require('../src/website-login');
const {encryptSecret}=require('../src/security');
const db=new DatabaseSync(':memory:');
db.exec(`CREATE TABLE workspaces(id TEXT PRIMARY KEY); INSERT INTO workspaces VALUES('owner'),('other');
CREATE TABLE audit_events(workspace_id TEXT,display_time TEXT,actor TEXT,action TEXT,outcome TEXT,detail TEXT);`);
const key=crypto.randomBytes(32), secret='synthetic-only-@#￥%';
const vault=createWebsiteVault(db);vault.save('owner',encryptSecret(secret,key,'owner:website-default:v1').envelope,'test');
const service=createWebsiteLogin(db,key);
const pair=crypto.generateKeyPairSync('rsa',{modulusLength:4096});
const body={origin:'https://example.test',confirmOrigin:'https://example.test',username:'synthetic-user',publicKey:pair.publicKey.export({format:'jwk'})};
const open=sealed=>crypto.privateDecrypt({key:pair.privateKey,oaepHash:'sha256',padding:crypto.constants.RSA_PKCS1_OAEP_PADDING},Buffer.from(sealed,'base64')).toString();
assert.throws(()=>service.begin('owner','test',{...body,origin:'http://example.test'}));
assert.throws(()=>service.begin('owner','test',{...body,confirmOrigin:'https://evil.test'}));
assert.throws(()=>service.begin('other','test',body));
let attempt=service.begin('owner','test',body);
assert.equal(attempt.source,'default');assert.equal(open(attempt.sealed),secret);
assert.ok(!JSON.stringify(attempt).includes(secret));assert.equal(service.list('owner').length,0);
assert.throws(()=>service.finish('other','test',{attemptId:attempt.attemptId,origin:body.origin,success:true,confirm:'LOGIN_CONFIRMED'}));
assert.throws(()=>service.finish('owner','test',{attemptId:attempt.attemptId,origin:body.origin,success:true}));
service.finish('owner','test',{attemptId:attempt.attemptId,origin:body.origin,success:false});
assert.equal(service.list('owner').length,0);
assert.throws(()=>service.finish('owner','test',{attemptId:attempt.attemptId,origin:body.origin,success:true,confirm:'LOGIN_CONFIRMED'}));
attempt=service.begin('owner','test',body);
service.finish('owner','test',{attemptId:attempt.attemptId,origin:body.origin,success:true,confirm:'LOGIN_CONFIRMED'});
assert.equal(service.list('owner').length,1);assert.equal(service.list('other').length,0);
vault.save('owner',encryptSecret('changed-default',key,'owner:website-default:v1').envelope,'test');
attempt=createWebsiteLogin(db,key).begin('owner','test',body);
assert.equal(attempt.source,'saved');assert.equal(open(attempt.sealed),secret);
service.disable('owner','test',body);assert.throws(()=>service.begin('owner','test',body));
const manual=service.begin('owner','test',{...body,manualSecret:'本人填的假密码'});
service.finish('owner','test',{attemptId:manual.attemptId,origin:body.origin,success:true,confirm:'LOGIN_CONFIRMED'});
assert.equal(open(service.begin('owner','test',body).sealed),'本人填的假密码');
const before=Date.now;let expired=service.begin('owner','test',body);Date.now=()=>before()+301000;
assert.throws(()=>service.finish('owner','test',{attemptId:expired.attemptId,origin:body.origin,success:true,confirm:'LOGIN_CONFIRMED'}));Date.now=before;
assert.ok(!JSON.stringify(db.prepare('SELECT * FROM audit_events').all()).includes(secret));
assert.ok(!Buffer.from(db.prepare('SELECT ciphertext FROM website_accounts').get().ciphertext).toString().includes(secret));
db.close();console.log('Website login: encrypted delivery, saved-first fallback, no save on failure, confirmation, expiry, isolation, disable and manual replacement passed');
